services:
  docquizz:
    image: docquiz-app
    build: ./
    container_name: DocQuizzAPI
    ports:
      - "3000:3000"
    volumes:
      - ./apps/quiz-app/src:/usr/src/app/src
      - ./libs:/usr/src/app/libs
    command: bash -c "npm run build && node dist/src/main"
    dns:
      - 8.8.8.8 # Google DNS
      - 8.8.4.4 # Google DNS
    env_file:
      - .env

  admin-panel:
    image: admin-panel
    build: ./
    container_name: AdminPanelAPI
    ports:
      - "3001:3000"
    volumes:
      - ./apps/admin/src:/usr/src/app/src
      - ./libs:/usr/src/app/libs
    command: bash -c "npm run build && node dist/src/main"
    env_file:
      - .env
    dns:
      - 8.8.8.8 # Google DNS
      - 8.8.4.4 # Google DNS