# Use the official Node.js 20 image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the necessary application code to the working directory
COPY . .

# Copy the content of the 'src' and 'libs' directories
COPY ./apps/quiz-app/src /usr/src/app/src
COPY ./libs /usr/src/app/libs

# Delete the './apps' directory to clean up the image
RUN rm -rf ./apps

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start"]
